-- Seed file: 001_seed_categories.sql
-- Inserts 100 categories for the IdeaNax idea marketplace platform.

INSERT INTO categories (name, slug, description) VALUES
('Technology', 'technology', 'Technology and software ideas'),
('Healthcare', 'healthcare', 'Healthcare and medical innovations'),
('Education', 'education', 'Education and learning solutions'),
('Finance', 'finance', 'Financial services and money management'),
('Agriculture', 'agriculture', 'Farming and agricultural innovations'),
('Food & Beverage', 'food-beverage', 'Food and drink industry ideas'),
('Fashion', 'fashion', 'Fashion and apparel innovations'),
('Entertainment', 'entertainment', 'Entertainment and media experiences'),
('Sports', 'sports', 'Sports and athletic ventures'),
('Travel', 'travel', 'Travel and tourism innovations'),
('Real Estate', 'real-estate', 'Real estate and property solutions'),
('Automotive', 'automotive', 'Automotive and vehicle innovations'),
('Energy', 'energy', 'Energy production and distribution'),
('Environment', 'environment', 'Environmental protection and conservation'),
('Social Impact', 'social-impact', 'Social good and community impact'),
('E-commerce', 'e-commerce', 'Online commerce and digital retail'),
('Marketing', 'marketing', 'Marketing and advertising strategies'),
('Media', 'media', 'Media production and distribution'),
('Gaming', 'gaming', 'Video games and interactive entertainment'),
('Music', 'music', 'Music creation and distribution'),
('Art & Design', 'art-design', 'Art, design, and creative services'),
('Architecture', 'architecture', 'Architecture and building design'),
('Legal', 'legal', 'Legal services and compliance'),
('Insurance', 'insurance', 'Insurance products and services'),
('Logistics', 'logistics', 'Logistics and transportation management'),
('Manufacturing', 'manufacturing', 'Manufacturing and production processes'),
('Robotics', 'robotics', 'Robotics and automation systems'),
('AI & Machine Learning', 'ai-machine-learning', 'Artificial intelligence and machine learning solutions'),
('Blockchain', 'blockchain', 'Blockchain and distributed ledger technology'),
('Cybersecurity', 'cybersecurity', 'Cybersecurity and data protection'),
('IoT', 'iot', 'Internet of Things devices and platforms'),
('AR/VR', 'ar-vr', 'Augmented reality and virtual reality experiences'),
('Space Tech', 'space-tech', 'Space exploration and satellite technology'),
('Biotech', 'biotech', 'Biotechnology and biological engineering'),
('Pharmaceuticals', 'pharmaceuticals', 'Pharmaceutical and drug development'),
('Mental Health', 'mental-health', 'Mental health and psychological well-being'),
('Fitness & Wellness', 'fitness-wellness', 'Fitness, wellness, and healthy living'),
('Home & Living', 'home-living', 'Home improvement and household solutions'),
('Pet Care', 'pet-care', 'Pet care products and services'),
('Beauty & Cosmetics', 'beauty-cosmetics', 'Beauty, skincare, and cosmetics'),
('Children & Kids', 'children-kids', 'Products and services for children'),
('Senior Care', 'senior-care', 'Elder care and senior living solutions'),
('Non-Profit', 'non-profit', 'Non-profit and charitable organizations'),
('Government', 'government', 'Government and public sector innovations'),
('Defense', 'defense', 'Defense and national security technology'),
('Telecom', 'telecom', 'Telecommunications and connectivity'),
('SaaS', 'saas', 'Software as a Service platforms'),
('Marketplace', 'marketplace', 'Marketplace and platform business models'),
('Subscription Services', 'subscription-services', 'Subscription-based products and services'),
('On-Demand Services', 'on-demand-services', 'On-demand and gig economy services'),
('Fintech', 'fintech', 'Financial technology and digital payments'),
('Edtech', 'edtech', 'Educational technology and e-learning'),
('Healthtech', 'healthtech', 'Health technology and digital health'),
('Proptech', 'proptech', 'Property technology and real estate tech'),
('Agritech', 'agritech', 'Agricultural technology and smart farming'),
('Cleantech', 'cleantech', 'Clean technology and green energy'),
('Legaltech', 'legaltech', 'Legal technology and digital law services'),
('Insurtech', 'insurtech', 'Insurance technology and digital insurance'),
('HR Tech', 'hr-tech', 'Human resources technology and recruitment'),
('Supply Chain', 'supply-chain', 'Supply chain management and optimization'),
('Retail', 'retail', 'Retail and in-store experiences'),
('Hospitality', 'hospitality', 'Hospitality and hotel industry solutions'),
('Aviation', 'aviation', 'Aviation and aerospace innovations'),
('Maritime', 'maritime', 'Maritime and ocean industry solutions'),
('Mining', 'mining', 'Mining and natural resource extraction'),
('Textiles', 'textiles', 'Textile and fabric manufacturing'),
('Furniture', 'furniture', 'Furniture design and home furnishings'),
('Electronics', 'electronics', 'Consumer electronics and hardware'),
('Wearables', 'wearables', 'Wearable technology and smart devices'),
('Smart Home', 'smart-home', 'Smart home automation and connected living'),
('3D Printing', '3d-printing', '3D printing and additive manufacturing'),
('Drones', 'drones', 'Drone technology and aerial systems'),
('Autonomous Vehicles', 'autonomous-vehicles', 'Self-driving and autonomous vehicle technology'),
('Quantum Computing', 'quantum-computing', 'Quantum computing and advanced processing'),
('Nanotechnology', 'nanotechnology', 'Nanotechnology and molecular engineering'),
('Data Analytics', 'data-analytics', 'Data analytics and business intelligence'),
('Cloud Computing', 'cloud-computing', 'Cloud infrastructure and services'),
('DevOps', 'devops', 'DevOps practices and CI/CD tooling'),
('Mobile Apps', 'mobile-apps', 'Mobile application development'),
('Web3', 'web3', 'Web3 and decentralized internet'),
('DeFi', 'defi', 'Decentralized finance and open protocols'),
('NFT & Digital Art', 'nft-digital-art', 'NFTs and digital art collectibles'),
('Creator Economy', 'creator-economy', 'Creator tools and monetization platforms'),
('Social Media', 'social-media', 'Social media and online communities'),
('Content Creation', 'content-creation', 'Content creation and digital publishing'),
('Podcasting', 'podcasting', 'Podcasting and audio content'),
('Event Management', 'event-management', 'Event planning and management solutions'),
('Wedding & Celebrations', 'wedding-celebrations', 'Wedding planning and celebration services'),
('Photography', 'photography', 'Photography and visual media'),
('Publishing', 'publishing', 'Book and digital publishing'),
('Translation', 'translation', 'Translation and localization services'),
('Tutoring', 'tutoring', 'Tutoring and personal education'),
('Coaching', 'coaching', 'Life and business coaching services'),
('Consulting', 'consulting', 'Professional consulting services'),
('Freelancing', 'freelancing', 'Freelancing and independent work platforms'),
('Co-working', 'co-working', 'Co-working spaces and shared offices'),
('Remote Work', 'remote-work', 'Remote work tools and solutions'),
('Sustainability', 'sustainability', 'Sustainable development and eco-friendly solutions'),
('Recycling', 'recycling', 'Recycling and waste management'),
('Water Tech', 'water-tech', 'Water purification and management technology');
